### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by XuYang1337** [tarimoe/blackjump#1]
请把
if ctx.baseurl.startswith("http"):
            c_pool = urllib3.HTTPConnectionPool
        else:
            c_pool = urllib3.HTTPSConnectionPool
改为
if ctx.baseurl.startswith("https"):
            c_pool = urllib3.HTTPSConnectionPool
        else:
            c_pool = urllib3.HTTPConnectionPool

也许https的开头也是http呀 ;D

**Comment by tarimoe** [comment]
感谢修正 @XuYang1337
